default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: devrails
  password: <%= ENV['BOOKS_ZONE_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: books_zone_development

test:
  <<: *default
  database: books_zone_test

production:
  <<: *default
  database: books_zone_production
